# Generated by Django 5.1.3 on 2025-01-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
