# Generated by Django 5.1.3 on 2024-12-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearcreadito',
            name='nPagos',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
