# Generated by Django 5.1.3 on 2024-11-30 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodo_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Pago', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('documento', models.PositiveIntegerField()),
                ('num_pagos', models.PositiveSmallIntegerField()),
                ('num_pagos_total', models.PositiveSmallIntegerField()),
                ('producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.productos')),
                ('metodo_pago', models.ManyToManyField(blank=True, to='abono.metodo_pago')),
            ],
        ),
    ]
