# Generated by Django 5.1 on 2024-11-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0002_alter_productos_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodo_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Pago', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('documento', models.PositiveIntegerField()),
                ('num_pagos', models.PositiveSmallIntegerField()),
                ('producto', models.ManyToManyField(blank=True, to='tienda.productos')),
                ('metodo_pago', models.ManyToManyField(blank=True, to='abono.metodo_pago')),
            ],
        ),
    ]
