# Generated by Django 5.1 on 2024-11-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abono', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='num_pagos_total',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
